<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Sudoku Solver - Load Sudoku Game</title>
        
        <link rel="stylesheet" href="../css/sudoku.css" />
        <link rel="stylesheet" href="../css/bootstrap.min.css" />
        <script src="../js/jquery-3.1.0.min.js"></script>
    </head>
    <body>
        <?php
            $parsedGrid = json_decode($grid) ;
            $size = $parsedGrid->size ;
        ?>

        <script>
            $(document).ready(function() {
                var grid = JSON.parse(JSON.stringify(<?php echo $grid; ?>)) ;
                for(i=0; i<grid.tiles.length; i++) {
                    var tile = grid.tiles[i] ;
                    var element = document.getElementById('t.'+tile.row+'.'+tile.col) ;
                    element.value = tile.value ; 
                    element.setAttribute("readonly", "readonly") ;
                }
            });
        
    </script>


<table class="sudoku_grid">
    <?php
        for($row = 0; $row < $size; $row++)
        {
    ?>
        <tr>
            <?php
                for($col = 0; $col < $size; $col++)
                {
                    $topStyle = '' ;
                    $leftStyle = '' ;
                    
                    if($row % sqrt($size) == 0) {
                        $topStyle = " region_border_top" ;
                    }
                    if($col % sqrt($size) == 0) {
                        $leftStyle = " region_border_left" ;
                    }
            ?>
                <td class="sudoku_case<?php echo $topStyle ;?><?php echo $leftStyle ;?>"><input type="text" class="case" size="1" name="t[<?php echo $row ; ?>][<?php echo $col ; ?>]" id="t.<?php echo $row ; ?>.<?php echo $col ; ?>" value=""/></td>
            <?php
                }
            ?>
        </tr>
    <?php
        }
    ?>
</table>
    <button id="newGameButton"  class="btn btn-default" type="submit" name="newGame" value="newGame">New Game</button>
    <button id="playGameButton"  class="btn btn-default" type="submit" name="play" value="Play">Play</button>

    </body>

    <script>
        $("#newGameButton").click(function() {
            location.href= "<?php echo $router->pathFor('game.start') ; ?>" ;
        }) ;

    </script>
</html>