<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>Sudoku Solver - Home</title>
        
        <link rel="stylesheet" href="../css/sudoku.css" />
        <link rel="stylesheet" href="../css/bootstrap.min.css" />
        <script src="../js/jquery-3.1.0.min.js"></script>
    </head>
    <body>

        <h1>Sudoku Solver</h1>
        <h2>Edition 2019</h2>
        
        <ul>
            <li><a href="Grid">Ajouter des nouvelles grilles</a></li>
            <li><a href="Game">Résoudre les grilles</a></li>
        </ul>
        
    </body>
    <footer>(c) haclong 2019</footer>
</html>